export const DOCUMENT_ERROR_CODES = {
  MISSING_FILE: "MISSING_FILE",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  NOT_RETRYABLE: "NOT_RETRYABLE",
} as const;
export type DocumentErrorCode = (typeof DOCUMENT_ERROR_CODES)[keyof typeof DOCUMENT_ERROR_CODES];
